export const themes = {
    'beige': 'beige',
    'black-contrast': 'black-contrast',
    'black': 'black',
    'blood': 'blood',
    'dracula': 'dracula',
    'league': 'league',
    'moon': 'moon',
    'night': 'night',
    'serif': 'serif',
    'simple': 'simple',
    'sky': 'sky',
    'solarized': 'solarized',
    'white': 'white',
    'white-contast': 'white-contast',
}
